services:
  - type: web
    name: gem-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    plan: free
    region: singapore
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: FIREBASE_PROJECT_ID
        value: bidder-fdede
      - key: FIRESTORE_DATABASE_ID
        value: (default)
      - key: GOOGLE_DRIVE_ROOT_FOLDER_ID
        value: 1Avm4vK0pwYcbaKvaqz5pXpUgsxuRULi4
      - key: GOOGLE_SHEET_PAN_ID
        value: 1S4f3wEKykvZ7LSM8vA129YqNKK9q3dlj
      - key: GOOGLE_SHEET_UDYAM_ID
        value: 1BaLtUC4K7R89UmFK3vHkyGAB-c0HmKNV
      - key: GOOGLE_SHEET_GST_ID
        value: 1EsWtSXWNNNwXcgG1wIhmGIQTJ6Tq89B8
      - key: GOOGLE_SHEET_OEM_ID
        value: 1Vo78YziNt6o4LN4d2BzuwVaPvugFaSOF
      - key: GOOGLE_SERVICE_ACCOUNT_JSON_BASE64
        sync: false
