// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYZ6yznn4WK6e9bQNAN6lQ6hHI5uYZOTA',
    appId: '1:996432007039:web:26ae0179c61a4d967c144a',
    messagingSenderId: '996432007039',
    projectId: 'bidder-fdede',
    authDomain: 'bidder-fdede.firebaseapp.com',
    storageBucket: 'bidder-fdede.firebasestorage.app',
    measurementId: 'G-0WWZMZ71N4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQknsuhGd7oqZ8Rt86DhvklhhtSrirQWg',
    appId: '1:996432007039:android:fe11be10d1aab65f7c144a',
    messagingSenderId: '996432007039',
    projectId: 'bidder-fdede',
    storageBucket: 'bidder-fdede.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCavS9D4Ru09gJwRTqw056jRpCcdDGCfDQ',
    appId: '1:996432007039:ios:3d32e0578590c5ea7c144a',
    messagingSenderId: '996432007039',
    projectId: 'bidder-fdede',
    storageBucket: 'bidder-fdede.firebasestorage.app',
    iosClientId: '996432007039-3m3bd7sp3njkhadlk04nq3hv5d6uev2n.apps.googleusercontent.com',
    iosBundleId: 'in.gov.gem.compliance.bidderApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCavS9D4Ru09gJwRTqw056jRpCcdDGCfDQ',
    appId: '1:996432007039:ios:3d32e0578590c5ea7c144a',
    messagingSenderId: '996432007039',
    projectId: 'bidder-fdede',
    storageBucket: 'bidder-fdede.firebasestorage.app',
    iosClientId: '996432007039-3m3bd7sp3njkhadlk04nq3hv5d6uev2n.apps.googleusercontent.com',
    iosBundleId: 'in.gov.gem.compliance.bidderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYZ6yznn4WK6e9bQNAN6lQ6hHI5uYZOTA',
    appId: '1:996432007039:web:62c09fe577e20f447c144a',
    messagingSenderId: '996432007039',
    projectId: 'bidder-fdede',
    authDomain: 'bidder-fdede.firebaseapp.com',
    storageBucket: 'bidder-fdede.firebasestorage.app',
    measurementId: 'G-3310TV8TLN',
  );
}
